# Generated by Django 5.1.4 on 2025-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_permision_bit_user_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permision_bit',
            field=models.BinaryField(null=True),
        ),
    ]
