# Generated by Django 5.1.4 on 2025-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermapping',
            name='name',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
